from .mongo import CoinTelegrapMongoPipeline
from .mongo import CoindeskMongoPipeline
from .mongo import NewsBtcMongoPipeline
from .mongo import BitcoinistMongoPipeline
from .mongo import TrustNodesMongoPipeline
from .mongo import EthereumWorldNewsMongoPipeline
from .mongo import NewsBitcoinMongoPipeline
from .mongo import BitNewsTodayMongoPipeline
from .mongo import InvestopediaMongoPipeline
from .mongo import MoneyAndStateMongoPipeline
from .mongo import BlogEthereumMongoPipeline
from .image import CoindeskImagePipeline
from .image import CoinTelegrapImagePipeline
from .image import NewsBtcImagePipeline
from .image import BitcoinistImagePipeline
from .image import TrustNodesImagePipeline
from .image import EthereumWorldNewsImagePipeline
from .image import NewsBitcoinImagePipeline
from .image import BitNewsTodayImagePipeline
from .image import InvestopediaImagePipeline
from .image import MoneyAndStateImagePipeline
from .image import BlogEthereumImagePipeline
