version: '2'
services:
  back:
    restart: always
    build: ./back/.
    command: sh docker-run-web.sh
    env_file: ./back/docker-env.ini
    working_dir: /app/
    volumes:
      - ./back:/app
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
      - celery
    expose:
      - 5432
      - 6379
      - 27017

  celery:
    build:
      context: ./back/
      dockerfile: Dockerfile-celery
    command: sh docker-run-celery.sh
    env_file: ./back/docker-env.ini
    working_dir: /app/
    volumes:
      - ./back:/app
    links:
      - redis:redis
    depends_on:
      - redis
    expose:
      - 6379
      - 27017

  redis:
    image: redis
    expose:
      - 6379

  db:
    image: 'postgres:9.6'
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: blocktimes
      POSTGRES_USER: blocktimes
      POSTGRES_PASSWORD: Blockttt81
    volumes:
      - ./db/data:/var/lib/postgresql/data

  nginx:
    build: ./nginx/.
    restart: always
    volumes:
      - ./back/run:/opt/run

      # Statics
      - ./admin/dist:/var/www/html/admin
      - ./back/media:/var/www/html/media
      - ./back/static:/var/www/html/static

      # Service
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs

      # Configs
      - ./nginx/confs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/confs/proxy_params:/etc/nginx/proxy_params
      - ./nginx/confs/static_params:/etc/nginx/static_params

      # Sites
      - ./nginx/sites-enabled/main.conf:/etc/nginx/sites-enabled/main.conf
      - ./nginx/sites-enabled/admin.conf:/etc/nginx/sites-enabled/admin.conf
    depends_on:
      - back
      - kibana
    expose:
      - 5601
    ports:
      - 8080:80
      - 443:443

  elasticsearch:
    build: log_server/elasticsearch/
    volumes:
      - ./log_server/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build: log_server/logstash/
    volumes:
      - ./nginx/logs:/tmp/nginx_logs
      - ./log_server/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./log_server/logstash/pipeline:/usr/share/logstash/pipeline
    expose:
      - 5000
      - 9200
      - 9300
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build: log_server/kibana/
    volumes:
      - ./log_server/kibana/config/:/usr/share/kibana/config
    expose:
      - 5000
      - 5601
    depends_on:
      - logstash
      - elasticsearch
    ports:
      - 5601:5601