version: '2'
services:
  back:
    restart: always
    build: ./back/.
    command: sh docker-run.sh
    working_dir: /app/
    volumes:
      - ./back:/app
    links:
      - db:db
      - mongo:mongo
    depends_on:
      - db
      - mongo
    expose:
      - 5432
      - 27017
    environment:
      PYTHONUNBUFFERED: 1
      SECRET_KEY: xs(r1v@27my)yw$c+6aww0l+9h5q^dc&y%+jpiid0xbvr8jwd1
      DATABASE_URL: postgres://blocktimes:Blockttt81@db/blocktimes
      ALLOWED_HOSTS: back.blocktimes.io,localhost,127.0.0.1
      BASE_URL: http://blocktimes.io/
      NO_LOAD_ENV_FILE: 'yes'
      NO_LOAD_SETTINGS_LOCAL: 'yes'

  db:
    image: 'postgres:9.6'
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: blocktimes
      POSTGRES_USER: blocktimes
      POSTGRES_PASSWORD: Blockttt81

  mongo:
    image: 'mongo:latest'
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_DATA_DIR: /data/db

  nginx:
    build: ./nginx/.
    restart: always
    volumes:
      - ./back/run:/opt/run

      - ./back/media:/var/www/html/media
      - ./back/static:/var/www/html/static

      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/static_params:/etc/nginx/static_params
      - ./nginx/back.conf:/etc/nginx/sites-enabled/back.conf
    depends_on:
      - back
      - mongo-admin
    links:
      - mongo-admin:mongo-admin
    ports:
      - 80:80
    expose:
      - 6800

  scrapyd:
    build: ./scrapyd/.
    restart: always
    working_dir: /scrapyd
    depends_on:
      - mongo
    links:
      - mongo:mongo
    environment:
      MONGO_DATABASE: blocktimes
      IMAGES_STORE: /var/lib/scrapyd
      MONGO_URI: mongodb://mongo:27017/blocktimes
    expose:
      - 6800
      - 27017
    volumes:
      - ./scrapyd/:/scrapyd
      - ./back/media:/var/lib/scrapyd
