version: '2'
services:
  back:
    restart: always
    build: ./back/.
    command: sh docker-run.sh
    environment:
      SECRET_KEY: xs(r1v@27my)yw$c+6aww0l+9h5q^dc&y%+jpiid0xbvr8jwd1
      DATABASE_URL: postgres://blocktimes:Blockttt81@db/blocktimes
      ALLOWED_HOSTS: blocktimes.io,admin.blocktimes.io,localhost,127.0.0.1
      NO_LOAD_ENV_FILE: 'yes'
      NO_LOAD_SETTINGS_LOCAL: 'yes'
      FB_KEY: b13688f1ed57735b28450287606d7269
    working_dir: /app/
    volumes:
      - ./back:/app
    links:
      - db:db
      - redis:redis
      - graylog:graylog
    depends_on:
      - db
      - redis
      - graylog
    expose:
      - 5000
      - 5432
      - 6379
      - 27017

      # Graylog2
      - 12201
      - 12201/udp

  redis:
    image: redis
    expose:
      - 6379

  db:
    image: 'postgres:9.6'
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: blocktimes
      POSTGRES_USER: blocktimes
      POSTGRES_PASSWORD: Blockttt81
    volumes:
      - ./db/data:/var/lib/postgresql/data

  nginx:
    build: ./nginx/.
    restart: always
    volumes:
      - ./back/run:/opt/run

      # Statics
      - ./admin/dist:/var/www/html/admin
      - ./back/media:/var/www/html/media
      - ./back/static:/var/www/html/static

      # Service
      - ./nginx/certs:/etc/nginx/certs

      # Configs
      - ./nginx/confs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/confs/proxy_params:/etc/nginx/proxy_params
      - ./nginx/confs/static_params:/etc/nginx/static_params

      # Sites
      - ./nginx/main.conf:/etc/nginx/sites-enabled/main.conf
    depends_on:
      - back
      - graylog
    links:
      - graylog:graylog
    expose:
      - 5601

      - 12301
      - 12301/udp

      - 12302
      - 12302/udp
    ports:
      - 80:80
      - 443:443

  mongodb:
    image: mongo:3
    volumes:
      - ./mongo/data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    image: graylog/graylog:2.3.2-1
    volumes:
      - ./graylog/journal:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # admin U4aB3shNMo4LG9NVwqsQ
      - GRAYLOG_ROOT_PASSWORD_SHA2=5a163b92d33486af3f6034b0145e1aee867f912381108bdaaa20294807fe00b4
      - GRAYLOG_WEB_ENDPOINT_URI=http://dev.tsrpay.com:9000//api
    links:
      - mongodb:mongo
      - elasticsearch:elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    expose:
      - 514
      - 514/udp

      - 9000

      # Back
      - 12201
      - 12201/udp

      # Nginx error
      - 12301
      - 12301/udp

      # Nginx access
      - 12302
      - 12302/udp
    ports:
      - 9000:9000
