version: '2'
services:
  back:
    restart: always
    build: ./back/.
    command: sh docker-run.sh
    environment:
      SECRET_KEY: xs(r1v@27my)yw$c+6aww0l+9h5q^dc&y%+jpiid0xbvr8jwd1
      DATABASE_URL: postgres://blocktimes:Blockttt81@db/blocktimes
      ALLOWED_HOSTS: blocktimes.io,admin.blocktimes.io,localhost,127.0.0.1
      NO_LOAD_ENV_FILE: 'yes'
      NO_LOAD_SETTINGS_LOCAL: 'yes'
      FB_KEY: b13688f1ed57735b28450287606d7269
    working_dir: /app/
    volumes:
      - ./back:/app
    links:
      - db:db
      - redis:redis
      - logstash:logstash
    depends_on:
      - db
      - redis
      - logstash
    expose:
      - 5000
      - 5432
      - 6379
      - 27017

  redis:
    image: redis
    expose:
      - 6379

  db:
    image: 'postgres:9.6'
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: blocktimes
      POSTGRES_USER: blocktimes
      POSTGRES_PASSWORD: Blockttt81
    volumes:
      - ./db/data:/var/lib/postgresql/data

  nginx:
    build: ./nginx/.
    restart: always
    volumes:
      - ./back/run:/opt/run

      # Statics
      - ./admin/dist:/var/www/html/admin
      - ./back/media:/var/www/html/media
      - ./back/static:/var/www/html/static

      # Service
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs

      # Configs
      - ./nginx/confs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/confs/proxy_params:/etc/nginx/proxy_params
      - ./nginx/confs/static_params:/etc/nginx/static_params

      # Sites
      - ./nginx/site.conf:/etc/nginx/sites-enabled/site.conf
    depends_on:
      - back
      - kibana
    expose:
      - 5601
    ports:
      - 80:80
      - 443:443

  elasticsearch:
    build: ./elasticsearch/.
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build: ./logstash/.
    volumes:
      - ./nginx/logs:/tmp/nginx_logs
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    expose:
      - 5000
      - 9200
      - 9300
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana/.
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    expose:
      - 5000
      - 5601
    depends_on:
      - logstash
      - elasticsearch
