version: '2'
services:
  back:
    restart: always
    build: ./back/.
    command: sh docker-run.sh
    working_dir: /app/
    volumes:
      - ./back:/app
    links:
      - db:db
      - redis:redis
      - mongo:mongo
    depends_on:
      - db
      - redis
      - mongo
      - celery
      - celery-beat
    expose:
      - 5432
      - 6379
      - 27017
    env_file: ./back/docker-env.ini

  db:
    image: 'postgres:9.6'
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: blocktimes
      POSTGRES_USER: blocktimes
      POSTGRES_PASSWORD: Blockttt81
    volumes:
      - ./db/data:/var/lib/postgresql/data

  mongo:
    image: 'mongo:latest'
    restart: always
    expose:
      - 27017
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_DATA_DIR: /data/db

  mongo_admin:
    image: mongo-express
    links:
      - mongo:mongo
    ports:
      - 8081:8081
    expose:
      - 8081
      - 27017
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://mongo:27017/blocktimes'
      ME_CONFIG_OPTIONS_EDITORTHEME: 'ambiance'
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'NxFaXl6Zvoszs7WP1tNI'

  nginx:
    build: ./nginx/.
    restart: always
    volumes:
      - ./back/run:/opt/run

      - ./admin/dist:/var/www/html/admin

      - ./back/media:/var/www/html/media
      - ./back/static:/var/www/html/static

      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/static_params:/etc/nginx/static_params
      - ./nginx/main.conf:/etc/nginx/sites-enabled/main.conf

      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - back
    ports:
      - 80:80
      - 443:443

  celery:
    build:
      context: ./back/
      dockerfile: Dockerfile-celery
    command: celery -A project worker -l info --pidfile="run/celery.pid" --logfile="logs/celery.log"
    working_dir: /app/
    volumes:
      - ./back:/app
      - ./crawler:/crawler
    env_file: ./back/docker-env.ini
    links:
      - redis:redis
      - mongo:mongo
    depends_on:
      - redis
      - mongo
    expose:
      - 6379
      - 27017

  celery-beat:
    build:
      context: ./back/
      dockerfile: Dockerfile-celery
    command: celery -A project beat -l info --logfile="logs/celery-beat.log" --pidfile="run/celery-beat.pid" --schedule="run/celerybeat-schedule"
    working_dir: /app/
    volumes:
      - ./back:/app
      - ./crawler:/crawler
    env_file: ./back/docker-env.ini
    links:
      - redis:redis
      - mongo:mongo
    depends_on:
      - redis
      - mongo
    expose:
      - 6379
      - 27017

  redis:
    image: redis
    expose:
      - 6379
