# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171030_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_main_image'),
        ),
    ]
