# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171113_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='coef',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
