# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ed', 'Editor'), ('pub', 'Publisher'), ('user', 'Simple user')], default='pub', max_length=4),
        ),
    ]
