---
- name: Upload configs
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - build-essential
    - libpcre3
    - libpcre3-dev
    - libssl-dev

- name: Restart nginx container
  shell: restart nginx container
