---
- name: Deploy new server
  gather_facts: no

  vars:
    git_url: git@bitbucket.org:drmartiner/blocktimes.git
    repo_dir: /opt/app/
    service_to_up: nginx

  vars_prompt:
  - name: 'git_ssh_key_path'
    prompt: 'GitHub key path'
    default: '~/.ssh/blocktimes_git_api'

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

  tasks:
    # Check exists GitHub SSH key files
    - stat:
      path: {{ git_ssh_key }}
      register: git_key_priv_path
    - debug:
      msg: 'GitHub SSH private key does not exists'
      when: git_key_priv_path.stat.exists is not defined

    - stat:
      path: {{ git_ssh_key }}.pub
      register: git_key_pub_path
    - debug:
      msg: 'GitHub SSH public key does not exists'
      when: git_key_pub_path.stat.exists is not defined

    # Install packages
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Add repository "universe"
      apt_repository: repo='universe' state=present
    - name: Install the packages
      apt: name={{ item }} state=present
      sudo: yes
      with_items:
        - mc
        - gcc
        - make
        - software-properties-common
        - git
        - lynx
        - htop
        - nmap
        - curl
        - bash-completion
        - docker
        - docker-compose

    - name: Add bash-completion script to ~/.bashrc
      lineinfile: dest=~/.bashrc line='{{item}}'
      with_items:
        - 'if ! shopt -oq posix; then'
        - '  if [ -f /usr/share/bash-completion/bash_completion ]; then'
        - '    . /usr/share/bash-completion/bash_completion'
        - '  elif [ -f /etc/bash_completion ]; then'
        - '    . /etc/bash_completion'
        - '  fi'
        - 'fi'

    - name: Stop redundant services
      with_items:
        - apache
        - postfix
        - rpcbind

    # Copy keys files
    # TODO: change id_rsa.* to id_rsa-github.*
    - name: Copy ~/.ssh/id_rsa.pub to ~/.ssh/authorized_keys
      copy: src=~/.ssh/id_rsa.pub
            dest=~/.ssh/authorized_keys
            owner=root group=root mode=u=rw,g=,o=
    - name: Copy GitHub private key
      copy: src={{ item.src.path }} dest=~/.ssh/{{ item.dest }}
            owner=root group=root mode=u=rw,g=,o=
      with_items:
        - { src: '{{ git_key_pub_path }}', dest: 'id_rsa.pub' }
        - { src: '{{ git_key_priv_path }}', dest: 'id_rsa' }
    - name: Clone repo
      git: repo={{ git_url}} dest=/opt/app
           accept_hostkey=yes force=yes recursive=no

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Run docker-compose
      command: docker-compose {{ item }}
      args:
        chdir: {{ repo_dir }}
      with_items:
        - build
        - up -d {{ service_to_up }}
