# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage', '0002_auto_20171115_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
