# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('long', 'Long post')], default='news', max_length=8),
        ),
    ]
