version: '2'
services:
  web:
    build: .
    restart: always
    command: sh /app/run_web.sh
    volumes:
      - .:/app
    links:
      - db:db
      - redis:redis
    ports:
      - 8000:8000
    expose:
      - 5432
      - 6379
    environment:
      - DB_URL=postgres://blocktimes:aG6PvGesnI@localhost/blocktimes
      - SECRET_KEY=123
      - ALLOWED_HOSTS=blocktimes.com
      - BASE_URL=https://blocktimes.com/
  db:
    image: 'postgres:9.6'
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=blocktimes
      - POSTGRES_USER=blocktimes
      - POSTGRES_PASSWORD=aG6PvGesnI
  redis:
    image: redis:latest
    expose:
      - 6379
