version: '2'
services:
  web:
    restart: always
    build: .
    command: sh docker-run-web.sh
    working_dir: /app/
    volumes:
      - .:/app
    links:
      - db:db
    ports:
      - 8000:8000
      - 127.0.0.1:27018:27018
    expose:
      - 5432
      - 8000
    environment:
      PYTHONUNBUFFERED: 1
      SECRET_KEY: xs(r1v@27my)yw$c+6aww0l+9h5q^dc&y%+jpiid0xbvr8jwd1
      DATABASE_URL: postgres://blocktimes:Blockttt81@localhost/blocktimes
      ALLOWED_HOSTS: blocktimes.com,localhost,127.0.0.1
      BASE_URL: https://blocktimes.com/

      NO_LOAD_ENV_FILE: 'yes'
      NO_LOAD_SETTINGS_LOCAL: 'yes'
  db:
    image: 'postgres:9.6'
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: blocktimes
      POSTGRES_USER: blocktimes
      POSTGRES_PASSWORD: Blockttt81
